spring:
  datasource:
    wf:
      username: hankun
      password: Hankun0421.
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.107.137.149:3306/wf?serverTimezone=CTT
    test:
      username: hankun
      password: Hankun0421.
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.107.137.149:3306/test?serverTimezone=CTT
  mail:
    host: smtp.163.com
    username: hankun_0421@163.com
    password: Hankun0421
    port: 465
  rabbitmq:
    host: 47.107.137.149
    port: 15672
    username: hankun
    password: Hankun0421

mybatis:
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

server:
  port: 917
