spring:
# 设置date返回数据为时间戳
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    wf:
      username: hankun
      password: Hankun0421.
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.107.137.149:3306/wf?serverTimezone=CTT # 多数据源需要jdbc-url 单数据源url
    test:
      username: hankun
      password: Hankun0421.
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.107.137.149:3306/test?serverTimezone=CTT # 多数据源需要jdbc-url 单数据源url
  mail:
    host: smtp.163.com
    username: hankun_0421@163.com
    password: Hankun0421
    port: 465
  rabbitmq:
    host: 47.107.137.149
    port: 15672
    username: hankun
    password: Hankun0421
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 10
        keep-alive: 60s
        max-size: 20
        queue-capacity: 40
      thread-name-prefix: 'Thread-'

# 多数据源需要分别单设置参数
mybatis:
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    wf:
      map-underscore-to-camel-case: true
      use-generated-keys: true
    test:
      map-underscore-to-camel-case: true
      use-generated-keys: true

server:
  port: 917
